### ISSUE TITLE
rabbitmq support

### ISSUE THREAD

**Issue by anandsunderraman** [comtihon/catcher#19]
After looking at the docs or at the catcher modules I do not see support for rabbitmq.

Is there a plan for rabbitmq support ? Are there guide lines to create a new module ?

**Comment by comtihon** [comment]
Hi,
yes, rabbit support is planned (maybe in 1-2 weeks it will be done).
As for guidelines, currently [here](https://catcher-test-tool.readthedocs.io/en/latest/source/modules.html) is the only info about custom modules.
You can also check catcher-modules repo for examples. F.e. recent [PR](https://github.com/comtihon/catcher_modules/pull/9) with s3 support.

**Comment by anandsunderraman** [comment]
@comtihon thanks for the prompt response. I will wait on the rabbitmq support
